plugin:
  view-secret:
    shortCut: Shift-S
    confirm: false
    description: "Secret"
    scopes:
      - deploy
      - sts
    command: sh
    background: false
    args:
      - -c
      - "kubectl --context $CONTEXT get secrets -n $NAMESPACE $NAME -o json | jq '{name: .metadata.name,data: .data|map_values(@base64d)}' | view -"
  view-configmap:
    shortCut: Shift-C
    confirm: false
    description: "ConfigMap"
    scopes:
      - deploy
      - sts
    command: sh
    background: false
    args:
      - -c
      - "kubectl --context $CONTEXT get configmaps -n $NAMESPACE $NAME -o json | view -"
