# themes from https://github.com/alacritty/alacritty-theme

# import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

# Colors (Gruvbox dark)

[shell]
program = "/opt/homebrew/bin/bash"

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
# red     = '#cc241d'
red     = '#bb3629'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[font]
size = 14

[font.normal]
family = "Hack Nerd Font"

[window]
decorations = "none"
dimensions = { columns = 184, lines =  49 }
position = { x = 20, y = 20 }
dynamic_padding = true
padding = { x = 2, y = 2 }
startup_mode = "Maximized"

[terminal]
osc52 = "CopyPaste"
